### ISSUE TITLE
Adapting for odroid

### ISSUE THREAD

**Issue by vallettea** [xdissent/pihotenuse#2]
I'm exploring the capabilities with an rpi but I'm ultimately interested to port the code for odroid-c1.
Do you think it is possible? easy? a few hints would be welcomed.

**Comment by xdissent** [comment]
Oh wow, I'd love to talk to you un-publicly about this idea. I think c'est possible mai probably hard. But that's what we're here for! Have you realized that the latest rpi is arm7? Fun times!?

**Comment by vallettea** [comment]
ok you have a tweeter ?

**Comment by xdissent** [comment]
tweet @xdissent brother. thank you again!
